config/routes.rb
Rails.application.routes.draw do
  resources :spaces, except: [:new, :edit, :update], param: :slug, shallow: true do
    resources :categories
    resources :lists, except: [:index] do
      get 'css', on: :member
      get 'example', on: :member
      resources :tokens, except: [:new, :show]
    end
  end
  root 'home#show'
  get ':slug', to: 'spaces#show'
end

app/models/list.rb
class List < ApplicationRecord
  has_many :tokens, dependent: :destroy
  belongs_to :space
  has_one_attached :stylesheet

  validates :name, presence: true

  def generate_css
    array = []

    self.tokens.each do |token|
      array << "  --#{token.name.parameterize}: #{token.value};\n"
    end

    stylesString = ":root {\n#{array.join}}"
    io = StringIO.new stylesString

    self.stylesheet.attach(
      io: io,
      filename: 'styles.css',
      content_type: 'text/css'
    )
  end

  def set_example_project_url
    self.project_url = Rails.application.routes.url_helpers.example_list_url(self)
    self.save
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_space
  before_action :check_space_expiration
  before_action :set_list, only: [:show, :edit, :update, :destroy, :css, :example]
  layout 'example', only: [:example]

  def show
    @tokensByCategory = groupTokens(@list)
    @space = @list.space
  end

  def new
    @space = Space.find_by slug: params[:space_slug]
    @list = List.new
  end

  def edit
  end

  def create
    @space = Space.find_by slug: params[:space_slug]
    @list = @space.lists.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: @list }

        ActionCable.server.broadcast("space_#{@space.slug}", {
          message_type: 'list_create',
          list: @list
        })
      else
        format.html { render 'new' }
      end
    end
  end

  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }

        ActionCable.server.broadcast("space_#{@list.space.slug}", {
          message_type: 'list_update',
          list: @list
        })
      else
        format.html { render :show }
      end
    end
  end

  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to space_url(@list.space), notice: 'List deleted.' }
      format.json { head :no_content }
    end

    ActionCable.server.broadcast("space_#{@list.space.slug}", {
      message_type: 'list_destroy',
      list_id: @list.id
    })
  end

  def css
    if @list.stylesheet.attached?
      redirect_to url_for(@list.stylesheet)
    else
      redirect_to @list
    end
  end

  def example
    if !@list.stylesheet.attached?
      redirect_to @list
    end
  end

  private

    def set_space
      list = List.find_by(id: params[:id])

      if list
        @space = list.space
      else
        @space = Space.find_by(slug: params[:space_slug]) || nil
      end
    end

    def set_list
      @list = List.find(params[:id])
    end

    def check_space_expiration
      if @space
        if @space.expired?
          respond_to do |format|
            format.html { render 'spaces/expired', status: :gone }
            format.json { render 'spaces/expired', status: :gone }
          end
        end
      else
        respond_to do |format|
          format.html { render 'other/404', status: :not_found }
          format.json { render 'other/404', status: :not_found }
        end
      end
    end

    def list_params
      params.require(:list).permit(:name, :space_slug, :description, :project_url)
    end

    def groupTokens(list)
      result = []

      list.space.categories.order('order_id').each do |category|
        object = {}
        object['category'] = category
        object['tokens'] = category.tokens.where(list_id: list.id).order('LOWER(name)')
        result << object
      end

      unless list.tokens.where(category_id: nil).empty?
        object = {}
        object['category'] = nil
        object['tokens'] = list.tokens.where(category_id: nil).order('LOWER(name)')
        result << object
      end

      result
    end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_form.html.erb
<%= form_with(model: model, local: true, class: 'form') do |form| %>
  <% if list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(list.errors.count, "error") %>:</h2>

      <ul>
        <% list.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form__input">
    <%= form.label :name, class: 'form__label' %>
    <%= form.text_field :name, placeholder: 'Unicorn Tokens', class: 'form__field' %>
  </div>

  <div class="form__input">
    <%= form.label :description, 'Description (optional)', class: 'form__label' %>
    <%= form.text_area :description, class: 'form__field form__field_multiline' %>
  </div>

  <div class="form__input">
    <%= form.label :project_url, 'Project URL (optional)', class: 'form__label' %>
    <%= form.url_field :project_url, 
      placeholder: 'http://example.com',
      class: 'form__field' %>
  </div>

  <%= form.submit nil, class: 'form__submit-button button' %>
<% end %>

app/views/lists/edit.html.erb
<div class="edit-list-page">
  <nav class="edit-list-page__back-link">
    <%= link_to 'Back to list', @list %>
  </nav>

  <h1 class="edit-list-page__title">Edit list</h1>

  <div class="edit-list-page__form">
    <%= render 'form', list: @list, model: @list %>
  </div>
</div>

app/views/lists/example.html.erb
<div class="example">
  <aside class="example__info-wrapper">
    <div class="example__info-content">
      <h3 class="example__info-title">Tips</h3>
      <ul class="example__info-list">
        <li class="example__info-list-item ">
          This preview page lets you experience real-time token changes without having to start your own project.
        </li>
        <li class="example__info-list-item">
          None of the elements is interactive. But it lets you preview the token styles.
        </li>
        <li class="example__info-list-item">
          Click the <svg class="example__info-list-item-symbol" height="24" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg"><g fill="none" fill-rule="evenodd"><circle cx="12" cy="12" fill="#0f0817" r="12"/><circle cx="12" cy="12" fill="#302c35" r="10.285714"/><path d="m11.7857145 5.14285714-5.78812399 2.55109641 5.78812399 2.54575675 5.7881244-2.54575675zm-6.21428593 10.26860026 5.86904783 2.5885426v-7.1612864l-5.86904783-2.58318751zm6.55952413-4.5727438v7.1612864l5.8690476-2.5885426v-7.15593131z" fill="#eae7ee" fill-rule="nonzero"/></g></svg> button in the bottom right corner to change the active token list.
        </li>
        <li class="example__info-list-item ">
          Change token values in <i class="example__info-semantically-different">Tokenhost 3000</i> and see updated styles applied to this page in real time. Having the browser tabs side by side helps.
        </li>
        <li class="example__info-list-item">
          Example: change <b class="example__info-important">color-interactive-primary</b> to <b class="example__info-important">tomato</b>.
        </li>
        <li class="example__info-list-item">
          Example: change <b class="example__info-important">radius-large</b> to <b class="example__info-important">36</b>.
        </li>
        <li class="example__info-list-item">
          Example: change <b class="example__info-important">color-background-surface</b> to <b class="example__info-important">transparent</b>.
        </li>
        <li class="example__info-list-item">
          Example: change <b class="example__info-important">font-size-medium</b> to <b class="example__info-important">30</b>.
        </li>
        <li class="example__info-list-item">
          Example: change <b class="example__info-important">spacing-medium</b> to <b class="example__info-important">40</b>.
        </li>
      </ul>
    </div>
  </aside>

  <header class="page-header">
    <h1>🦸🏽‍♀️🦸🏿‍♂️ Superhero Cards</h1>
  </header>

  <main>
    <header>
      <h2 class="text-secondary"><%= Faker::Movies::StarWars.quote %></h2>
      <p class="text-tertiary"><%= Faker::Movies::StarWars.wookiee_sentence %></p>
      <button class="button-primary" id="light-theme-button">Add a Card</button>
      <button class="button-secondary" id="dark-theme-button">Ask a Question</button>
    </header>
    <section>
      <ul class="superhero-cards-wrapper">
        <% 50.times do %>
          <li class="superhero-card">
            <h3 class="text-primary"><%= Faker::Superhero.name %></h3>
            <h4 class="text-secondary"><%= Faker::Superhero.power %></h4>
            <p class="text-tertiary"><%= Faker::Address.city %></p>
          </li>
        <% end %>
      </ul>
    </section>
  </main>

  <footer>
    <p><%= Faker::Books::Dune.quote %></p>
  </footer>
</div>

app/views/lists/new.html.erb
<div class="new-list-page">
  <nav class="new-list-page__back-link">
    <%= link_to 'Back to lists', @space %>
  </nav>

  <h1 class="new-list-page__title">Create List</h1>

  <div class="new-list-page__form">
    <%= render 'form', list: @list, model: [@space, @list] %>
  </div>
</div>

app/views/lists/show.html.erb
<div class="list-page">
  <nav class="list-page__back-link">
    <%= link_to 'Back to lists', space_path(@list.space) %>
  </nav>
  <header class="list-page__header">
    <h1 class="list-page__title"><%= @list.name %></h1>
    <p class="list-page__meta-info">
      <span class="list-page__token-count"><%= @list.tokens.size %> <%= 'token'.pluralize @list.tokens.size %></span>
      <% if @list.stylesheet.attached? %>
        <span class="list-page__meta-info-separator">·</span>
        <span class="list-page__meta-info-css">
          <%= link_to 'CSS Link', css_list_url(@list) %>
        </span>
      <% end %>
      <% if @list.project_url.present? %>
        <span class="list-page__meta-info-separator">·</span>
        <span class="list-page__meta-info-project-url">
          <a href="<%= @list.project_url %>", target="_blank">Preview Project</a>
        </span>
      <% end %>
    </p>
    <% if @list.description %>
      <p class="list-page__description"><%= @list.description %></p>
    <% end %>
    <div class="list-page__edit-name-pill">
      <div class="pill-actions">
        <%= link_to 'Edit', edit_list_path(@list), class: 'pill-actions__item' %>
        <%= link_to 'Delete', list_path(@list), method: :delete, data: { confirm: 'Delete list? This can’t be undone.' }, class: 'pill-actions__item' %>
      </div>
    </div>
  </header>

  <section class="list-page__add-token-section">
    <h2 class="list-page__add-token-section-title">Create a new token</h2>
    <div class="list-page__add-token-form">
      <%= render 'tokens/form', model: [@list, @list.tokens.new], list: @list, form_url: list_tokens_path(@list) %>
    </div>
  </section>

  <section class="list-page__tokens-section">
    <% @tokensByCategory.each do |obj| %>
      <div class="list-page__token-category">
        <h2 class="list-page__token-category-title <%= 'list-page__token-category-title_empty' if obj['tokens'].empty? %>">
          <%= obj['category'].nil? ? 'No Category' : obj['category']['name'] %>
        </h2>
        <p class="list-page__token-category-count <%= 'list-page__token-category-count_empty' if obj['tokens'].empty? %>">
          <%= obj['tokens'].size %> <%= 'token'.pluralize obj['tokens'].size %>
        </p>
        <% if !obj['category'].nil? %>
          <div class="list-page__token-category-actions pill-actions">
            <%= link_to 'Edit', edit_category_path(obj['category'], list_id: @list.id), class: 'pill-actions__item' %>
            <%= link_to 'Delete', category_path(obj['category'], list_id: @list.id),
                        method: :delete, class: 'pill-actions__item' %>
          </div>
        <% end %>

        <div class="list-page__token-category-grid">
          <% obj['tokens'].each do |token| %>
            <div class="card">
              <%= render 'tokens/token', token: token %>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </section>

  <section class="list-page__add-category-section">
    <h2 class="list-page__add-category-section-title">New category</h2>
    <div class="list-page__add-category-form">
      <%= render 'categories/form', model: [@space, @space.categories.new], category: @space.categories.new, list_id: @list.id %>
    </div>
  </section>
</div>