config/routes.rb
Rails.application.routes.draw do
  resources :spaces, except: [:new, :edit, :update], param: :slug, shallow: true do
    resources :categories
    resources :lists, except: [:index] do
      get 'css', on: :member
      get 'example', on: :member
      resources :tokens, except: [:new, :show]
    end
  end
  root 'home#show'
  get ':slug', to: 'spaces#show'
end

app/models/space.rb
class Space < ApplicationRecord
  has_many :lists, dependent: :destroy
  has_many :categories, dependent: :destroy

  EXPIRATION_TIME_HOURS = 48
  SECONDS_IN_AN_HOUR = 3600

  before_create :set_slug
  after_create :create_sample_categories, :create_sample_lists

  def to_param
    slug
  end

  def expired?
    hours_until_expiration < 0
  end

  def hours_until_expiration
    total_seconds = EXPIRATION_TIME_HOURS * SECONDS_IN_AN_HOUR
    elapsed_seconds = Time.now - self.created_at
    hours = (total_seconds - elapsed_seconds) / SECONDS_IN_AN_HOUR
    hours.floor
  end

  private

    def generate_slug
      array = []

      3.times { array << Faker::Creature::Animal.unique.name.parameterize }
      Faker::UniqueGenerator.clear

      array.join('-')
    end

    def set_slug
      loop do
        self.slug = generate_slug
        break unless Space.where(slug: slug).exists?
      end
    end

    def create_sample_categories
      seed_categories = YAML::load_file('db/seeds/categories.yml')
      seed_categories.each do |category|
        self.categories.create!(name: category['name'])
      end
    end

    def create_sample_lists
      lists = YAML::load_file("db/seeds/lists.yml")

      lists.each do |seed|
        create_list(seed['name'], seed['description'], seed['tokens'])
      end
    end

    def create_list(name, description, tokens)
      sample_list = self.lists.new(name: name, description: description)

      tokens.each do |token|
        category = self.categories.find_by(name: token['category'])

        if category
          token['category_id'] = category.id
        end

        token.delete 'category'
      end
      sample_list.tokens.new(tokens)
      sample_list.save
      sample_list.set_example_project_url
      sample_list.generate_css
    end
end

app/controllers/spaces_controller.rb
class SpacesController < ApplicationController
  http_basic_authenticate_with name: ENV['BASIC_AUTH_USER'], password: ENV['BASIC_AUTH_PASSWORD'], only: [:destroy, :index]

  before_action :check_space_expiration, only: [:show]

  def index
    @spaces = Space.all
  end

  def show
    @space = Space.find_by slug: params[:slug]
  end

  def create
    @space = Space.new

    if @space.save
      redirect_to @space, notice: 'Space created. Enjoy!'
    else
      render 'home/show'
    end
  end

  def destroy
    @space = Space.find_by slug: params[:slug]
    @space.destroy
    respond_to do |format|
      format.html { redirect_to spaces_url, notice: 'Space deleted.' }
      format.json { head :no_content }
    end
  end

  private

    def check_space_expiration
      space = Space.find_by slug: params[:slug]

      if space
        if space.expired?
          respond_to do |format|
            format.html { render 'spaces/expired', status: :gone }
            format.json { render 'spaces/expired', status: :gone }
          end
        end
      else
        respond_to do |format|
          format.html { render 'other/404', status: :not_found }
          format.json { render 'other/404', status: :not_found }
        end
      end
    end
end

app/helpers/spaces_helper.rb
module SpacesHelper

  def expiration_string(space)
    hours = space.hours_until_expiration

    case hours
    when (1..)
      "Expires in about #{hours} #{'hour'.pluralize(hours)}"
    when 0
      "Expires in less than an hour"
    when (..-1)
      "This space has expired"
    else
      ""
    end
  end
end

app/views/spaces/_space.html.erb
<div class="space-list-item">
  <p>
    <%= link_to "Space ##{space.id}", space %>
    <%= link_to 'Delete', space, method: :delete %>
  </p>
</div>

app/views/spaces/expired.html.erb
<div class="expired-space-page">
  <h2 class="expired-space-page__title">Space expired.</h2>
</div>

app/views/spaces/index.html.erb
<div class="spaces-page">
  <h1>Spaces</h1>
  <div class="spaces-page__list">
    <%= render @spaces %>
  </div>
  <div class="actions">
    <%= form_with model: Space.new, local: true do |form| %>
      <%= form.submit class: "actions__item" %>
    <% end %>
  </div>
</div>

app/views/spaces/not_found.html.erb
<h1>Couldn’t find this space. Sorry, boo.</h1>

app/views/spaces/show.html.erb
<div class="space-page">
  <header class="space-page__header">
    <h1 class="space-page__title">Space</h1>
    <h3 class="space-page__subtitle"><%= @space.slug %></h3>
    <p class="space-page__info-label"><%= expiration_string(@space) %></p>
  </header>

  <section class="space-page__section">
    <% if @space.lists.empty? %>
      <p class="space-page__no-tokens-text">There are no token lists in this space. Go ahead and create one.</p>
    <% else %>
      <h3>Lists of tokens</h3>
      <ul class="space-page__list-of-lists">
        <% @space.lists.each do |list| %>
          <li class="space-page__list-item">
            <%= link_to list.name, list_path(list), class: 'space-page__list-item-link' %>
          </li>
        <% end %>
      </ul>
    <% end %>

    <div class="space-page__actions actions">
      <%= link_to 'Create list', new_space_list_path(@space), class: 'actions__item' %>
    </div>
  </section>

  <section class="space-page__section space-page__usage-section">
    <h2 class="space-page__usage-section-title">Usage & FAQ</h2>

    <section class="space-page__section">
      <h3>Deliver tokens from one particular list as CSS</h3>
      <p class="space-page__info-paragraph">
        Every list of tokens comes with a link to a CSS file. Every token you create in Tokenhost 3000 is applied as a custom CSS property set on the root (HTML) element.
      </p>

      <p class="space-page__info-paragraph">
        So the moment you link to this CSS file from your HTML, you can access all of the tokens by their names.
      </p>
    </section>

    <section class="space-page__section">
      <h3>Apply CSS styles at runtime</h3>
      <p class="space-page__info-paragraph">
        Include the following script tag inside the head tag of your HTML. It will render a widget on the page. The widget lets you change the currently active list of tokens, so you can compare different sets of styles.
      </p>

      <pre class="code-block">
        <code>
          <%= "<script src='https://cdn.jsdelivr.net/gh/andyjakubowski/tm3000-widget@0.1-alpha/widget.js' id='tokenhub-widget' data-space='#{@space.slug}' data-api='#{Rails.configuration.token_api_url}' data-cable='#{Rails.configuration.action_cable.url}'></script>" %>
        </code>
      </pre>

      <p class="space-page__info-paragraph">
        The widget applies the changes in real time. That means you can keep your project open in one browser tab, and edit the styles in Tokenhost 3000 inside another tab. All the changes you make will be applied to your project immediately.
      </p>
    </section>

    <section class="space-page__section">
      <h3>Access and edit tokens via an API</h3>
      <p class="space-page__info-paragraph">
        You can use the Tokenhost 3000 API to do anything you can do using the web UI.
      </p>
    </section>

    <section class="space-page__section">
      <h3>Link to this space</h3>
      <p class="space-page__info-paragraph"><%= link_to nil, space_url(@space) %></p>
      <p class="space-page__info-paragraph">
        Anyone with this link can access the space until it expires.
      </p>
    </section>

    <section class="space-page__section">
      <h3>Why do spaces expire?</h3>
      <p class="space-page__info-paragraph">
        Tokenhost 3000 is meant for experimentation. It’s not fully baked. You’re not meant to use it in a production app. Because of this, all spaces expire and can’t be accessed again after roughly 48 hours.
      </p>
    </section>
  </section>
</div>