config/routes.rb
Rails.application.routes.draw do
  resources :spaces, except: [:new, :edit, :update], param: :slug, shallow: true do
    resources :categories
    resources :lists, except: [:index] do
      get 'css', on: :member
      get 'example', on: :member
      resources :tokens, except: [:new, :show]
    end
  end
  root 'home#show'
  get ':slug', to: 'spaces#show'
end

app/models/token.rb
class Token < ApplicationRecord
  belongs_to :list
  belongs_to :category, optional: true

  def self.types
    [Color, FontSize, Spacing, BorderRadius]
  end
end

app/controllers/tokens_controller.rb
class TokensController < ApplicationController
  before_action :set_space
  before_action :check_space_expiration
  before_action :set_list, only: [:index, :create]

  def index
    @tokens = @list.tokens
  end

  def edit
    @token = Token.find(params[:id])
  end

  def create
    @token = @list.tokens.new(token_params)
    respond_to do |format|
      if @token.save
        @list.generate_css
        format.html { redirect_to list_path(@list), notice: 'Token created.' }
        format.json { render :show, status: :created, location: token_url(@token) }

        ActionCable.server.broadcast("space_#{@list.space.slug}", {
          message_type: 'token_create',
          token: @token
        })
      else
        format.html { render 'lists/show' }
        format.json { render json: @token.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @token = Token.find(params[:id])

    respond_to do |format|
      if @token.update(token_params)
        @token.list.generate_css
        format.html { redirect_to @token.list, notice: 'Token updated.' }
        format.json { render :show, status: :ok, location: token_url(@token) }

        ActionCable.server.broadcast("space_#{@token.list.space.slug}", {
          message_type: 'token_update',
          token: @token
        })
      else
        format.html { render 'edit' }
      end
    end
  end

  def destroy
    @token = Token.find(params[:id])
    @token.destroy

    @token.list.generate_css
    respond_to do |format|
      format.html { redirect_to @token.list, notice: 'Token deleted.' }
      format.json { head :no_content }
    end

    ActionCable.server.broadcast("space_#{@token.list.space.slug}", {
      message_type: 'token_destroy',
      token: @token
    })
  end

  private

    def set_space
      token = Token.find_by(id: params[:id])

      if token
        list = token.list
      else
        list = List.find_by(id: params[:list_id])
      end

      @space = list ? list.space : nil
    end

    def check_space_expiration
      if @space
        if @space.expired?
          respond_to do |format|
            format.html { render 'spaces/expired', status: :gone }
            format.json { render 'spaces/expired', status: :gone }
          end
        end
      else
        respond_to do |format|
          format.html { render 'other/404', status: :not_found }
          format.json { render 'other/404', status: :not_found }
        end
      end
    end

    def set_list
      @list = List.find(params[:list_id])
    end

    def token_params
      params.require(:token).permit(:name, :value, :category_id, :list_id, :type)
    end
end

app/helpers/tokens_helper.rb
module TokensHelper
  def token_types
    Token.types
  end

  def partial_name(token)
    path_prefix = 'tokens/visuals/'
    suffix = case token.type
              when 'Color'
                'color'
              when 'FontSize'
                'font_size'
              when 'Spacing'
                'spacing'
              when 'BorderRadius'
                'border_radius'
              else
                'no_type'
              end

    path_prefix + suffix
  end

  def modifier_for_visual(token)
    case token.type
    when 'Color'
      'color'
    when 'FontSize'
      'font-size'
    when 'Spacing'
      'spacing'
    when 'BorderRadius'
      'border-radius'
    else
      ''
    end
  end

  def styles_for_visual(token)
    case token.type
    when 'Color'
      "background-color: #{token.value};"
    when 'FontSize'
      "font-size: #{token.value}px;"
    when 'Spacing'
      "grid-gap: #{token.value}px; gap: #{token.value}px;"
    when 'BorderRadius'
      "border-radius: #{token.value}px;"
    else
      ''
    end
  end
end

app/views/tokens/_form.html.erb
<%= form_with model: model, scope: :token, url: form_url, local: true, class: 'form' do |form| %>
  <div class="form__input">
    <div class="form__input-description">
      <%= form.label :name, class: 'form__label' %>
      <p class="form__hint">Use lowercase letters only, separated by a dash “-”. The name has to begin and end with a letter.</p>
    </div>
    <%= form.text_field :name, class: 'form__field', pattern: '^[a-z]+(-[a-z]+)*$', required: '', placeholder: 'color-text-primary' %>
  </div>

  <div class="form__input">
    <div class="form__input-description">
      <%= form.label :value, class: 'form__label' %>
      <p class="form__hint">Use any value your project can interpret. For example, any valid CSS value if you’re using CSS.</p>
    </div>
    <%= form.text_field :value, class: 'form__field', placeholder: '#333333' %>
  </div>

  <div class="form__input">
    <div class="form__input-description">
      <%= form.label :type, class: 'form__label' %>
      <p class="form__hint">Used to visualize tokens. Use any value if you don’t pick any type. For the color type, use valid CSS color values (hex code, rgba() etc.). FontSize, Spacing and BorderRadius values must be whole, unitless numbers (skip the “px”).</p>
    </div>
    <%= form.collection_select(:type, token_types, :name, :name, include_blank: 'No Type') %>
  </div>

  <div class="form__input">
    <div class="form__input-description">
      <%= form.label :category_id, class: 'form__label' %>
      <p class="form__hint">Groups tokens into sections. Does not affect the token in any other way.</p>
    </div>
    <%= form.collection_select(:category_id, list.space.categories, :id, :name, include_blank: 'No Category') %>
  </div>

  <%= form.submit nil, class: 'form__submit-button button' %>
<% end %>

app/views/tokens/_token.html.erb
<div class="token">
  <div class="token__content">
    <div class="token__visual">
      <%= render partial_name(token), token: token %>
    </div>
    <div class="token__content-labels">
      <h3 class="token__value"><%= token.value %></h3>
      <p class="token__name"><%= token.name %></p>
    </div>
  </div>
  <div class="pill-actions">
    <%= link_to 'Edit', edit_token_path(token), class: 'pill-actions__item' %>
    <%= link_to 'Delete', token_path(token),
                method: :delete, class: 'pill-actions__item' %>
  </div>
</div>

app/views/tokens/edit.html.erb
<div class="edit-token-page">
  <nav class="edit-token-page__back-link">
    <%= link_to 'Back to list', @token.list %>
  </nav>

  <h1 class="edit-token-page__title">Edit token</h1>

  <div class="edit-token-page__form">
    <%= render 'form', model: @token, list: @token.list, form_url: token_path(@token) %>
  </div>
</div>