config/routes.rb
Rails.application.routes.draw do
  resources :spaces, except: [:new, :edit, :update], param: :slug, shallow: true do
    resources :categories
    resources :lists, except: [:index] do
      get 'css', on: :member
      get 'example', on: :member
      resources :tokens, except: [:new, :show]
    end
  end
  root 'home#show'
  get ':slug', to: 'spaces#show'
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true
  has_many :tokens, dependent: :nullify
  belongs_to :space

  before_create :set_order_id

  private
    def set_order_id
      current_max_order_id = self.space.categories.map { |c| c.order_id }.max || 0
      self.order_id = current_max_order_id + 1
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_space
  before_action :check_space_expiration

  def index
    @categories = Category.all

    respond_to do |format|
      format.html { render 'other/404' }
      format.json { render :index, status: :ok }
    end
  end

  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
  end

  def edit
    @category = Category.find(params[:id])
    @list = List.find_by id: params[:list_id]
  end

  def create
    space = Space.find_by slug: params[:space_slug]
    list = List.find_by id: params[:list_id]
    @category = space.categories.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to list, notice: 'Category created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render 'new' }
      end
    end
  end

  def update
    list = List.find_by id: params[:list_id]
    @category = Category.find(params[:id])
    space = @category.space

    respond_to do |format|
      if @category.update(category_params)
        if list
          format.html { redirect_to list, notice: 'Edited category.' }
        else
          format.html { redirect_to space, notice: 'Edited category.' }
        end
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render 'edit' }
      end

    end
  end

  def destroy
    list = List.find(params[:list_id])
    category = Category.find(params[:id])
    category.destroy

    respond_to do |format|
      format.html { redirect_to list, notice: 'Category deleted.' }
      format.json { head :no_content }
    end
  end

  private

    def set_space
      category = Category.find_by(id: params[:id])

      if category
        @space = category.space
      else
        @space = Space.find_by(slug: params[:space_slug]) || nil
      end
    end

    def check_space_expiration
      if @space
        if @space.expired?
          respond_to do |format|
            format.html { render 'spaces/expired', status: :gone }
            format.json { render 'spaces/expired', status: :gone }
          end
        end
      else
        respond_to do |format|
          format.html { render 'other/404', status: :not_found }
          format.json { render 'other/404', status: :not_found }
        end
      end
    end

    def category_params
      params.require(:category).permit(:name, :space_slug)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<tr>
  <td><%= category.name %></td>
  <td><%= link_to 'Edit', edit_category_path(category) %></td>
  <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/categories/_form.html.erb
<%= form_with(model: model, local: true, class: 'form') do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% if list_id %>
    <input name="list_id" type="hidden" value="<%= list_id %>" />
  <% end %>

  <div class="form__input">
    <%= form.label :name, class: 'form__label' %>
    <%= form.text_field :name, class: 'form__field', required: '' %>
  </div>

  <%= form.submit nil, class: 'form__submit-button button' %>
<% end %>

app/views/categories/_list.html.erb
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%= render @categories %>
  </tbody>
</table>

app/views/categories/edit.html.erb
<div class="edit-category-page">
  <% if @list %>
    <nav class="edit-category-page__back-link">
      <%= link_to 'Back to list', @list %>
    </nav>
  <% else %>
    <nav class="edit-category-page__back-link">
      <%= link_to 'Back to space', @category.space %>
    </nav>
  <% end %>

  <h1 class="edit-category-page__title">Edit category</h1>

  <div class="edit-category-page__form">
    <%= render 'form', model: @category, category: @category, list_id: @list ? @list.id : nil %>
  </div>
</div>

app/views/categories/new.html.erb
<h1>Add New Category</h1>
<p>The Elders have waited for this for a long time 🧓🏽👴🏾👵🏻</p>

<%= render 'form', category: @category %>

<%= link_to 'Back to all lists', lists_path %>